name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  ci-cd:
    uses: winccoa-tools-pack/.github/.github/workflows/reusable-ci-cd.yml@main
    with:
      project_type: vscode
    secrets: inherit
