name: Release

on:
    workflow_run:
        workflows:
            - "CI/CD Pipeline"
            - "Integration Tests - WinCC OA"
        types:
            - completed
        branches:
            - main
    workflow_dispatch:
        inputs: {}

permissions:
    contents: write
    pull-requests: write
    packages: write
    actions: write
    checks: write
    issues: write

jobs:
    release:
        if: |
            github.event_name == 'workflow_dispatch' ||
            github.event.workflow_run.conclusion == 'success'
        uses: winccoa-tools-pack/.github/.github/workflows/reusable-release.yml@main
        with:
            target_branch: main
            project_type: vscode
        secrets: inherit
